// Một chỗ khai khoá cache, để mutation vô hiệu hoá đúng thứ mà màn hình đang đọc.
export const keys = {
  me: () => ["auth", "me"] as const,
  aiHealth: (days: number) => ["admin", "ai-health", days] as const,
  aiFailures: (query: unknown) => ["admin", "ai-failures", query] as const,
  aiFailureFacets: (range: unknown) => ["admin", "ai-failures", "facets", range] as const,
  aiCall: (id: string) => ["admin", "ai-call", id] as const,
  aiUsage: (days: number) => ["admin", "ai-usage", days] as const,
  overview: (days: number) => ["admin", "overview", days] as const,
  queueStats: () => ["queue", "stats"] as const,
  queueConfig: () => ["admin", "queue-config"] as const,
  portalHealth: (range: unknown) => ["admin", "scrape", "portals", range] as const,
  scrapeBatches: (query: unknown) => ["admin", "scrape", "batches", query] as const,
  skills: () => ["skills"] as const,
  users: (query: unknown) => ["admin", "users", query] as const,
  user: (id: string) => ["admin", "user", id] as const,
  jobs: (query: unknown) => ["admin", "jobs", query] as const,
  job: (id: string) => ["admin", "job", id] as const,
  jobSources: () => ["admin", "job-sources"] as const,
  dictionary: () => ["admin", "dictionary"] as const,
  dictionaryList: (query: unknown) => ["admin", "dictionary", "list", query] as const,
  dictionarySkill: (id: string) => ["admin", "dictionary", "skill", id] as const,
  dictionarySummary: () => ["admin", "dictionary", "summary"] as const,
};
